version: "3"

services:
{%- if cookiecutter.include_client == 'y' %}
  client:
    build:
      context: .
      dockerfile: ./ops/client/prod/Dockerfile
    ports:
      - "8080:8080"
    env_file: ./ops/client/prod/.env
  {%- endif %}

  {%- if cookiecutter.include_server == 'y' %}
  server:
    build:
      context: .
      dockerfile: ./ops/server/prod/Dockerfile
    depends_on:
      - database
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: ./ops/server/prod/.env

  database:
    image: postgres:14-alpine
    env_file: ./ops/database/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
  {%- endif %}
