version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./ops/server/Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: ./ops/server/.env

  traefik:
    image: traefik:4.6
  
  redis:
    image: redis:4.6
  
